ALTER TABLE employees ADD COLUMN IF NOT EXISTS custom_message TEXT DEFAULT '';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS show_photo_on_card INTEGER DEFAULT 1;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS reset_code_expires BIGINT DEFAULT 0;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS currency VARCHAR(10) DEFAULT 'MAD';
ALTER TABLE withdrawals ADD COLUMN IF NOT EXISTS admin_note TEXT DEFAULT '';
ALTER TABLE withdrawals ADD COLUMN IF NOT EXISTS currency VARCHAR(10) DEFAULT 'MAD';
