import { createContext, useContext, useState, useCallback, useEffect, type ReactNode } from 'react';
import { I18nManager } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';

I18nManager.allowRTL(true);

const LANGUAGE_KEY = 'snaptip_language';

const translations: Record<string, Record<string, string>> = {
  en: {
    // Navigation
    home: 'Home',
    tips: 'Tips',
    profile: 'Profile',
    // Home / Dashboard
    available_balance: 'Available Balance',
    total_earned: 'Total Earned',
    tips_received: 'Tips Received',
    tip_link_ready: 'Your tip link is ready',
    copy_link: 'Copy Link',
    share_qr: 'Share QR',
    manage_team: 'Manage Your Team',
    add_members: 'Add members, send invites',
    cash_out: 'Cash Out',
    my_qr: 'My QR',
    recent_tips: 'Recent Tips',
    view_all: 'View All',
    no_tips_yet: 'No tips yet',
    no_tips_desc: 'Share your QR code to start receiving tips from customers',
    show_my_qr: 'Show My QR',
    quick_actions: 'Quick Actions',
    my_qr_code_action: 'My QR Code',
    share_download_qr: 'Share & download your tip QR',
    withdraw_earnings: 'Withdraw Earnings',
    request_earnings_payout: 'Request your earnings payout',
    profile_settings: 'Profile & Settings',
    photo_name_language: 'Photo, name, language',
    // Profile
    my_profile: 'My Profile',
    settings_preferences: 'Settings & preferences',
    personal_info: 'Personal Info',
    full_name: 'Full Name',
    job_title: 'Job Title',
    save_profile: 'Save Profile',
    saving: 'Saving...',
    your_workplace: 'Your Workplace',
    member_account: 'Member account',
    active: 'Active',
    workplace_note: 'Your workplace can only be changed by your manager',
    withdrawal_settings: 'Withdrawal Settings',
    update_payment: 'Update Payment Method',
    payment_methods_desc: 'CIH Bank · Cash Plus · Wafa Cash',
    security: 'Security',
    change_password: 'Change Password',
    current_password: 'Current Password',
    new_password: 'New Password',
    confirm_password: 'Confirm New Password',
    save_password: 'Save Password',
    payment_method: 'Payment Method',
    rib_account: 'RIB / Account Number',
    enter_account: 'Enter account number',
    save_method: 'Save Method',
    account_settings: 'Account Settings',
    edit_profile: 'Edit Profile',
    business_settings: 'Business Settings',
    my_team: 'My Team',
    manage_members: 'Manage team members',
    invite_members: 'Invite Members',
    send_invitations: 'Send invitations',
    withdraw_funds: 'Withdraw Funds',
    recent_withdrawals: 'Recent Withdrawals',
    logout: 'Log Out',
    language: 'Language',
    change_photo: 'Change Photo',
    take_photo: 'Take Photo',
    choose_gallery: 'Choose from Gallery',
    settings: 'Settings',
    select_language: 'Select Language',
    // QR Card
    my_qr_card: 'My QR Card',
    download_share_subtitle: 'Download & share your printable tip card',
    download_share_card: 'Download & Share Card',
    preparing: 'Preparing...',
    preview_tourist_page: 'Preview Tourist Page',
    printing_tip: 'Printing tip',
    printing_tip_desc: 'Download the card as a PDF and print it for your table. Customers scan the QR to tip you — no app needed.',
    enjoyed: 'Enjoyed the service?',
    leave_tip: 'Leave a tip!',
    secure: 'Secure payment via SnapTip',
    select_amount: 'Choose tip amount',
    pay: 'Pay',
    save: 'Save',
    // Withdraw
    withdraw_title: 'Withdraw Earnings',
    request_payout: 'Request your payout',
    withdrawal_history: 'Withdrawal History',
    no_withdrawals: 'No withdrawals yet',
    no_withdrawals_desc: 'Your withdrawal history will appear here',
    amount: 'Amount',
    method: 'Method',
    submit_request: 'Submit Request',
    submitting: 'Submitting...',
    you_will_receive: 'You will receive:',
    available: 'Available:',
    enter_details: 'Enter account details',
    tip_received: 'Tip received',
    // Common
    cancel: 'Cancel',
    back: 'Back',
    confirm: 'Confirm',
    link_copied: 'Link copied!',
    // Tips screen
    tip_transactions: 'Tip Transactions',
    no_tips: 'No tips yet',
    share_qr_tips: 'Share your QR code to start receiving tips!',
    // Status
    pending: 'Pending',
    completed: 'Completed',
    rejected: 'Rejected',
    // ── Auth: Register ──────────────────────────────────────────────────────────
    reg_create_account: 'Create your account',
    reg_first_name: 'First name',
    reg_last_name: 'Last name',
    reg_email_ph: 'you@example.com',
    reg_send_code: 'Send Verification Code',
    reg_sending: 'Sending...',
    reg_secure: 'Secure & encrypted',
    reg_check_email: 'Check your email',
    reg_code_sent_to: 'We sent a 6-digit code to',
    reg_verify_code: 'Verify Code',
    reg_verifying: 'Verifying...',
    reg_change_email: '← Change email',
    reg_resend_code: 'Resend code',
    reg_create_creds: 'Create credentials',
    reg_username: 'username',
    reg_pw_min: 'Password (min 6 characters)',
    reg_confirm_pw: 'Confirm password',
    reg_account_type: 'Account Type',
    reg_individual: 'Individual',
    reg_i_work_alone: 'I work alone',
    reg_business_label: 'Business',
    reg_i_manage_team: 'I manage a team',
    reg_select_country: 'Select Your Country',
    reg_select_country_ph: 'Select your country',
    reg_create_btn: 'Create Account',
    reg_creating: 'Creating...',
    reg_back: '← Back',
    reg_add_photo: 'Add your photo',
    reg_add_photo_desc: 'Add a photo so customers can recognize you.',
    reg_change_photo: 'Change photo',
    reg_add_photo_btn: 'Add photo',
    reg_job_title_ph: 'Job title (e.g. Waiter, Tour Guide)',
    reg_complete_setup: 'Complete Setup',
    reg_skip: 'Skip for now',
    reg_profile_photo: 'Profile Photo',
    reg_already: 'Already have an account?',
    reg_login_link: 'Log in',
    // ── Auth: Login ─────────────────────────────────────────────────────────────
    login_welcome: 'Welcome back',
    login_email_user: 'Email or Username',
    login_password_label: 'Password',
    login_log_in: 'Log In',
    login_logging_in: 'Logging in...',
    login_forgot_pw: 'Forgot your password?',
    login_no_account: "Don't have an account?",
    login_sign_up: 'Sign up',
    // ── Auth: Forgot Password ───────────────────────────────────────────────────
    fp_reset_pw: 'Reset Password',
    fp_all_done: 'All Done!',
    fp_enter_email_hint: 'Enter your email to receive a reset code',
    fp_code_sent_to: 'We sent a 6-digit code to',
    fp_pw_reset_done: 'Your password has been reset',
    fp_email_label: 'Email Address',
    fp_email_ph: 'you@example.com',
    fp_code_label: 'Verification Code',
    fp_new_pw_label: 'New Password',
    fp_pw_min_ph: 'Min 6 characters',
    fp_confirm_pw_label: 'Confirm Password',
    fp_confirm_ph: 'Confirm password',
    fp_send_reset: 'Send Reset Code',
    fp_reset_btn: 'Reset Password',
    fp_resetting: 'Resetting...',
    fp_login_new_pw: 'Login with New Password',
    fp_back_to_email: 'Back to email',
    fp_back_to_login: 'Back to Login',
    fp_success_title: 'Password Reset Successfully!',
    fp_success_desc: 'You can now log in with your new password.',
  },
  fr: {
    home: 'Accueil',
    tips: 'Pourboires',
    profile: 'Profil',
    available_balance: 'Solde disponible',
    total_earned: 'Total gagné',
    tips_received: 'Pourboires reçus',
    tip_link_ready: 'Votre lien est prêt',
    copy_link: 'Copier le lien',
    share_qr: 'Partager QR',
    manage_team: 'Gérer votre équipe',
    add_members: 'Ajouter des membres',
    cash_out: 'Retirer',
    my_qr: 'Mon QR',
    recent_tips: 'Pourboires récents',
    view_all: 'Voir tout',
    no_tips_yet: 'Pas encore de pourboires',
    no_tips_desc: 'Partagez votre QR code pour recevoir des pourboires',
    show_my_qr: 'Afficher mon QR',
    quick_actions: 'Actions rapides',
    my_qr_code_action: 'Mon code QR',
    share_download_qr: 'Partager et télécharger votre QR',
    withdraw_earnings: 'Retirer les gains',
    request_earnings_payout: 'Demander un paiement',
    profile_settings: 'Profil et paramètres',
    photo_name_language: 'Photo, nom, langue',
    my_profile: 'Mon Profil',
    settings_preferences: 'Paramètres et préférences',
    personal_info: 'Informations personnelles',
    full_name: 'Nom complet',
    job_title: 'Poste',
    save_profile: 'Enregistrer le profil',
    saving: 'Enregistrement...',
    your_workplace: 'Votre lieu de travail',
    member_account: 'Compte membre',
    active: 'Actif',
    workplace_note: 'Votre lieu de travail ne peut être changé que par votre responsable',
    withdrawal_settings: 'Paramètres de retrait',
    update_payment: 'Modifier le moyen de paiement',
    payment_methods_desc: 'CIH Bank · Cash Plus · Wafa Cash',
    security: 'Sécurité',
    change_password: 'Changer le mot de passe',
    current_password: 'Mot de passe actuel',
    new_password: 'Nouveau mot de passe',
    confirm_password: 'Confirmer le nouveau mot de passe',
    save_password: 'Enregistrer le mot de passe',
    payment_method: 'Moyen de paiement',
    rib_account: 'RIB / Numéro de compte',
    enter_account: 'Entrer le numéro de compte',
    save_method: 'Enregistrer la méthode',
    account_settings: 'Paramètres du compte',
    edit_profile: 'Modifier le profil',
    business_settings: 'Paramètres entreprise',
    my_team: 'Mon équipe',
    manage_members: 'Gérer les membres',
    invite_members: 'Inviter des membres',
    send_invitations: 'Envoyer des invitations',
    withdraw_funds: 'Retirer des fonds',
    recent_withdrawals: 'Retraits récents',
    logout: 'Se déconnecter',
    language: 'Langue',
    change_photo: 'Changer la photo',
    take_photo: 'Prendre une photo',
    choose_gallery: 'Choisir depuis la galerie',
    settings: 'Paramètres',
    select_language: 'Choisir la langue',
    my_qr_card: 'Ma carte QR',
    download_share_subtitle: 'Téléchargez et partagez votre carte',
    download_share_card: 'Télécharger et partager',
    preparing: 'Préparation...',
    preview_tourist_page: 'Aperçu page touriste',
    printing_tip: "Conseil d'impression",
    printing_tip_desc: "Téléchargez la carte en PDF et imprimez-la pour votre table. Les clients scannent le QR pour vous donner un pourboire.",
    enjoyed: 'Vous avez apprécié le service?',
    leave_tip: 'Laissez un pourboire!',
    secure: 'Paiement sécurisé via SnapTip',
    select_amount: 'Choisir le montant',
    pay: 'Payer',
    save: 'Enregistrer',
    withdraw_title: 'Retirer les gains',
    request_payout: 'Demander votre paiement',
    withdrawal_history: 'Historique des retraits',
    no_withdrawals: 'Aucun retrait',
    no_withdrawals_desc: 'Votre historique de retraits apparaîtra ici',
    amount: 'Montant',
    method: 'Méthode',
    submit_request: 'Soumettre la demande',
    submitting: 'Envoi en cours...',
    you_will_receive: 'Vous recevrez :',
    available: 'Disponible :',
    enter_details: 'Entrer les détails du compte',
    tip_received: 'Pourboire reçu',
    cancel: 'Annuler',
    back: 'Retour',
    confirm: 'Confirmer',
    link_copied: 'Lien copié !',
    tip_transactions: 'Transactions',
    no_tips: 'Pas encore de pourboires',
    share_qr_tips: 'Partagez votre QR code !',
    pending: 'En attente',
    completed: 'Terminé',
    rejected: 'Rejeté',
    // ── Auth: Register ──────────────────────────────────────────────────────────
    reg_create_account: 'Créer votre compte',
    reg_first_name: 'Prénom',
    reg_last_name: 'Nom',
    reg_email_ph: 'vous@exemple.com',
    reg_send_code: 'Envoyer le code de vérification',
    reg_sending: 'Envoi...',
    reg_secure: 'Sécurisé et chiffré',
    reg_check_email: 'Vérifiez votre e-mail',
    reg_code_sent_to: 'Nous avons envoyé un code à 6 chiffres à',
    reg_verify_code: 'Vérifier le code',
    reg_verifying: 'Vérification...',
    reg_change_email: '← Changer l\'e-mail',
    reg_resend_code: 'Renvoyer le code',
    reg_create_creds: 'Créer vos identifiants',
    reg_username: 'nom d\'utilisateur',
    reg_pw_min: 'Mot de passe (min 6 caractères)',
    reg_confirm_pw: 'Confirmer le mot de passe',
    reg_account_type: 'Type de compte',
    reg_individual: 'Individuel',
    reg_i_work_alone: 'Je travaille seul',
    reg_business_label: 'Entreprise',
    reg_i_manage_team: 'Je gère une équipe',
    reg_select_country: 'Sélectionner votre pays',
    reg_select_country_ph: 'Sélectionner votre pays',
    reg_create_btn: 'Créer un compte',
    reg_creating: 'Création...',
    reg_back: '← Retour',
    reg_add_photo: 'Ajouter votre photo',
    reg_add_photo_desc: 'Ajoutez une photo pour que les clients vous reconnaissent.',
    reg_change_photo: 'Changer la photo',
    reg_add_photo_btn: 'Ajouter une photo',
    reg_job_title_ph: 'Poste (ex. Serveur, Guide touristique)',
    reg_complete_setup: 'Terminer la configuration',
    reg_skip: 'Ignorer pour l\'instant',
    reg_profile_photo: 'Photo de profil',
    reg_already: 'Vous avez déjà un compte ?',
    reg_login_link: 'Se connecter',
    // ── Auth: Login ─────────────────────────────────────────────────────────────
    login_welcome: 'Bon retour',
    login_email_user: 'E-mail ou nom d\'utilisateur',
    login_password_label: 'Mot de passe',
    login_log_in: 'Se connecter',
    login_logging_in: 'Connexion...',
    login_forgot_pw: 'Mot de passe oublié ?',
    login_no_account: 'Pas encore de compte ?',
    login_sign_up: "S'inscrire",
    // ── Auth: Forgot Password ───────────────────────────────────────────────────
    fp_reset_pw: 'Réinitialiser le mot de passe',
    fp_all_done: 'Tout est fait !',
    fp_enter_email_hint: 'Entrez votre e-mail pour recevoir un code de réinitialisation',
    fp_code_sent_to: 'Nous avons envoyé un code à 6 chiffres à',
    fp_pw_reset_done: 'Votre mot de passe a été réinitialisé',
    fp_email_label: 'Adresse e-mail',
    fp_email_ph: 'vous@exemple.com',
    fp_code_label: 'Code de vérification',
    fp_new_pw_label: 'Nouveau mot de passe',
    fp_pw_min_ph: 'Min 6 caractères',
    fp_confirm_pw_label: 'Confirmer le mot de passe',
    fp_confirm_ph: 'Confirmer le mot de passe',
    fp_send_reset: 'Envoyer le code de réinitialisation',
    fp_reset_btn: 'Réinitialiser le mot de passe',
    fp_resetting: 'Réinitialisation...',
    fp_login_new_pw: 'Se connecter avec le nouveau mot de passe',
    fp_back_to_email: "Retour à l'e-mail",
    fp_back_to_login: 'Retour à la connexion',
    fp_success_title: 'Mot de passe réinitialisé !',
    fp_success_desc: 'Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.',
  },
  ar: {
    home: 'الرئيسية',
    tips: 'إكراميات',
    profile: 'الملف',
    available_balance: 'الرصيد المتاح',
    total_earned: 'إجمالي الأرباح',
    tips_received: 'إكراميات مستلمة',
    tip_link_ready: 'رابط الإكرامية جاهز',
    copy_link: 'نسخ الرابط',
    share_qr: 'مشاركة QR',
    manage_team: 'إدارة فريقك',
    add_members: 'إضافة أعضاء',
    cash_out: 'سحب',
    my_qr: 'رمز QR',
    recent_tips: 'إكراميات أخيرة',
    view_all: 'عرض الكل',
    no_tips_yet: 'لا إكراميات بعد',
    no_tips_desc: 'شارك رمز QR لبدء استلام الإكراميات',
    show_my_qr: 'عرض رمز QR',
    quick_actions: 'إجراءات سريعة',
    my_qr_code_action: 'رمز QR الخاص بي',
    share_download_qr: 'مشاركة وتحميل رمز QR',
    withdraw_earnings: 'سحب الأرباح',
    request_earnings_payout: 'طلب صرف الأرباح',
    profile_settings: 'الملف والإعدادات',
    photo_name_language: 'الصورة, الاسم, اللغة',
    my_profile: 'ملفي الشخصي',
    settings_preferences: 'الإعدادات والتفضيلات',
    personal_info: 'المعلومات الشخصية',
    full_name: 'الاسم الكامل',
    job_title: 'المسمى الوظيفي',
    save_profile: 'حفظ الملف',
    saving: 'جاري الحفظ...',
    your_workplace: 'مكان عملك',
    member_account: 'حساب عضو',
    active: 'نشط',
    workplace_note: 'لا يمكن تغيير مكان عملك إلا من قبل مديرك',
    withdrawal_settings: 'إعدادات السحب',
    update_payment: 'تحديث طريقة الدفع',
    payment_methods_desc: 'CIH Bank · Cash Plus · Wafa Cash',
    security: 'الأمان',
    change_password: 'تغيير كلمة المرور',
    current_password: 'كلمة المرور الحالية',
    new_password: 'كلمة المرور الجديدة',
    confirm_password: 'تأكيد كلمة المرور',
    save_password: 'حفظ كلمة المرور',
    payment_method: 'طريقة الدفع',
    rib_account: 'RIB / رقم الحساب',
    enter_account: 'أدخل رقم الحساب',
    save_method: 'حفظ الطريقة',
    account_settings: 'إعدادات الحساب',
    edit_profile: 'تعديل الملف',
    business_settings: 'إعدادات العمل',
    my_team: 'فريقي',
    manage_members: 'إدارة الأعضاء',
    invite_members: 'دعوة أعضاء',
    send_invitations: 'إرسال دعوات',
    withdraw_funds: 'سحب الأموال',
    recent_withdrawals: 'سحوبات أخيرة',
    logout: 'تسجيل الخروج',
    language: 'اللغة',
    change_photo: 'تغيير الصورة',
    take_photo: 'التقاط صورة',
    choose_gallery: 'اختيار من المعرض',
    settings: 'الإعدادات',
    select_language: 'اختر اللغة',
    my_qr_card: 'بطاقة QR',
    download_share_subtitle: 'حمل وشارك بطاقتك القابلة للطباعة',
    download_share_card: 'تحميل ومشاركة البطاقة',
    preparing: 'جاري التحضير...',
    preview_tourist_page: 'معاينة صفحة الدفع',
    printing_tip: 'نصيحة للطباعة',
    printing_tip_desc: 'حمّل البطاقة كملف PDF واطبعها لطاولتك. يمسح العملاء رمز QR لإعطائك إكرامية.',
    enjoyed: 'هل استمتعت بالخدمة؟',
    leave_tip: '!اترك بقشيشاً',
    secure: 'دفع آمن عبر SnapTip',
    select_amount: 'اختر المبلغ',
    pay: 'ادفع',
    save: 'حفظ',
    withdraw_title: 'سحب الأرباح',
    request_payout: 'طلب صرف الأرباح',
    withdrawal_history: 'سجل السحوبات',
    no_withdrawals: 'لا توجد سحوبات',
    no_withdrawals_desc: 'سيظهر سجل السحوبات هنا',
    amount: 'المبلغ',
    method: 'الطريقة',
    submit_request: 'إرسال الطلب',
    submitting: 'جاري الإرسال...',
    you_will_receive: 'ستتلقى:',
    available: 'المتاح:',
    enter_details: 'أدخل تفاصيل الحساب',
    tip_received: 'إكرامية مستلمة',
    cancel: 'إلغاء',
    back: 'رجوع',
    confirm: 'تأكيد',
    link_copied: 'تم نسخ الرابط!',
    tip_transactions: 'المعاملات',
    no_tips: 'لا إكراميات بعد',
    share_qr_tips: 'شارك رمز QR لبدء استلام الإكراميات!',
    pending: 'قيد الانتظار',
    completed: 'مكتمل',
    rejected: 'مرفوض',
    // ── Auth: Register ──────────────────────────────────────────────────────────
    reg_create_account: 'إنشاء حسابك',
    reg_first_name: 'الاسم الأول',
    reg_last_name: 'اسم العائلة',
    reg_email_ph: 'you@example.com',
    reg_send_code: 'إرسال رمز التحقق',
    reg_sending: 'جاري الإرسال...',
    reg_secure: 'آمن ومشفر',
    reg_check_email: 'تحقق من بريدك الإلكتروني',
    reg_code_sent_to: 'أرسلنا رمزاً من 6 أرقام إلى',
    reg_verify_code: 'التحقق من الرمز',
    reg_verifying: 'جاري التحقق...',
    reg_change_email: '← تغيير البريد',
    reg_resend_code: 'إعادة إرسال الرمز',
    reg_create_creds: 'إنشاء بيانات الاعتماد',
    reg_username: 'اسم المستخدم',
    reg_pw_min: 'كلمة المرور (6 أحرف على الأقل)',
    reg_confirm_pw: 'تأكيد كلمة المرور',
    reg_account_type: 'نوع الحساب',
    reg_individual: 'فردي',
    reg_i_work_alone: 'أعمل بمفردي',
    reg_business_label: 'شركة',
    reg_i_manage_team: 'أدير فريقاً',
    reg_select_country: 'اختر دولتك',
    reg_select_country_ph: 'اختر دولتك',
    reg_create_btn: 'إنشاء حساب',
    reg_creating: 'جاري الإنشاء...',
    reg_back: '← رجوع',
    reg_add_photo: 'أضف صورتك',
    reg_add_photo_desc: 'أضف صورة حتى يتعرف عليك العملاء.',
    reg_change_photo: 'تغيير الصورة',
    reg_add_photo_btn: 'إضافة صورة',
    reg_job_title_ph: 'المسمى الوظيفي (مثال: نادل، مرشد سياحي)',
    reg_complete_setup: 'إكمال الإعداد',
    reg_skip: 'تخطي الآن',
    reg_profile_photo: 'صورة الملف الشخصي',
    reg_already: 'هل لديك حساب بالفعل؟',
    reg_login_link: 'تسجيل الدخول',
    // ── Auth: Login ─────────────────────────────────────────────────────────────
    login_welcome: 'مرحباً بعودتك',
    login_email_user: 'البريد الإلكتروني أو اسم المستخدم',
    login_password_label: 'كلمة المرور',
    login_log_in: 'تسجيل الدخول',
    login_logging_in: 'جاري الدخول...',
    login_forgot_pw: 'نسيت كلمة المرور؟',
    login_no_account: 'ليس لديك حساب؟',
    login_sign_up: 'إنشاء حساب',
    // ── Auth: Forgot Password ───────────────────────────────────────────────────
    fp_reset_pw: 'إعادة تعيين كلمة المرور',
    fp_all_done: 'تم بنجاح!',
    fp_enter_email_hint: 'أدخل بريدك الإلكتروني لاستلام رمز إعادة التعيين',
    fp_code_sent_to: 'أرسلنا رمزاً من 6 أرقام إلى',
    fp_pw_reset_done: 'تم إعادة تعيين كلمة مرورك',
    fp_email_label: 'البريد الإلكتروني',
    fp_email_ph: 'you@example.com',
    fp_code_label: 'رمز التحقق',
    fp_new_pw_label: 'كلمة المرور الجديدة',
    fp_pw_min_ph: '6 أحرف على الأقل',
    fp_confirm_pw_label: 'تأكيد كلمة المرور',
    fp_confirm_ph: 'تأكيد كلمة المرور',
    fp_send_reset: 'إرسال رمز الإعادة',
    fp_reset_btn: 'إعادة تعيين كلمة المرور',
    fp_resetting: 'جاري الإعادة...',
    fp_login_new_pw: 'الدخول بكلمة المرور الجديدة',
    fp_back_to_email: 'العودة للبريد',
    fp_back_to_login: 'العودة لتسجيل الدخول',
    fp_success_title: 'تمت إعادة تعيين كلمة المرور!',
    fp_success_desc: 'يمكنك الآن تسجيل الدخول بكلمة مرورك الجديدة.',
  },
  es: {
    home: 'Inicio',
    tips: 'Propinas',
    profile: 'Perfil',
    available_balance: 'Saldo disponible',
    total_earned: 'Total ganado',
    tips_received: 'Propinas recibidas',
    tip_link_ready: 'Tu enlace está listo',
    copy_link: 'Copiar enlace',
    share_qr: 'Compartir QR',
    manage_team: 'Gestionar equipo',
    add_members: 'Añadir miembros',
    cash_out: 'Retirar',
    my_qr: 'Mi QR',
    recent_tips: 'Propinas recientes',
    view_all: 'Ver todo',
    no_tips_yet: 'Sin propinas aún',
    no_tips_desc: 'Comparte tu QR para empezar a recibir propinas',
    show_my_qr: 'Mostrar mi QR',
    quick_actions: 'Acciones rápidas',
    my_qr_code_action: 'Mi código QR',
    share_download_qr: 'Comparte y descarga tu QR',
    withdraw_earnings: 'Retirar ganancias',
    request_earnings_payout: 'Solicitar pago de ganancias',
    profile_settings: 'Perfil y ajustes',
    photo_name_language: 'Foto, nombre, idioma',
    my_profile: 'Mi Perfil',
    settings_preferences: 'Ajustes y preferencias',
    personal_info: 'Información personal',
    full_name: 'Nombre completo',
    job_title: 'Cargo',
    save_profile: 'Guardar perfil',
    saving: 'Guardando...',
    your_workplace: 'Tu lugar de trabajo',
    member_account: 'Cuenta de miembro',
    active: 'Activo',
    workplace_note: 'Tu lugar de trabajo solo puede ser cambiado por tu gerente',
    withdrawal_settings: 'Ajustes de retiro',
    update_payment: 'Actualizar método de pago',
    payment_methods_desc: 'CIH Bank · Cash Plus · Wafa Cash',
    security: 'Seguridad',
    change_password: 'Cambiar contraseña',
    current_password: 'Contraseña actual',
    new_password: 'Nueva contraseña',
    confirm_password: 'Confirmar nueva contraseña',
    save_password: 'Guardar contraseña',
    payment_method: 'Método de pago',
    rib_account: 'RIB / Número de cuenta',
    enter_account: 'Ingresa el número de cuenta',
    save_method: 'Guardar método',
    account_settings: 'Configuración',
    edit_profile: 'Editar perfil',
    business_settings: 'Ajustes de negocio',
    my_team: 'Mi equipo',
    manage_members: 'Gestionar miembros',
    invite_members: 'Invitar miembros',
    send_invitations: 'Enviar invitaciones',
    withdraw_funds: 'Retirar fondos',
    recent_withdrawals: 'Retiros recientes',
    logout: 'Cerrar sesión',
    language: 'Idioma',
    change_photo: 'Cambiar foto',
    take_photo: 'Tomar foto',
    choose_gallery: 'Elegir de galería',
    settings: 'Configuración',
    select_language: 'Seleccionar idioma',
    my_qr_card: 'Mi tarjeta QR',
    download_share_subtitle: 'Descarga y comparte tu tarjeta imprimible',
    download_share_card: 'Descargar y compartir',
    preparing: 'Preparando...',
    preview_tourist_page: 'Vista previa página turista',
    printing_tip: 'Consejo de impresión',
    printing_tip_desc: 'Descarga la tarjeta como PDF e imprímela para tu mesa. Los clientes escanean el QR para darte propina.',
    enjoyed: '¿Disfrutaste el servicio?',
    leave_tip: '¡Deja una propina!',
    secure: 'Pago seguro via SnapTip',
    select_amount: 'Elige el monto',
    pay: 'Pagar',
    save: 'Guardar',
    withdraw_title: 'Retirar ganancias',
    request_payout: 'Solicitar tu pago',
    withdrawal_history: 'Historial de retiros',
    no_withdrawals: 'Sin retiros aún',
    no_withdrawals_desc: 'Tu historial de retiros aparecerá aquí',
    amount: 'Monto',
    method: 'Método',
    submit_request: 'Enviar solicitud',
    submitting: 'Enviando...',
    you_will_receive: 'Recibirás:',
    available: 'Disponible:',
    enter_details: 'Ingresa los datos de la cuenta',
    tip_received: 'Propina recibida',
    cancel: 'Cancelar',
    back: 'Volver',
    confirm: 'Confirmar',
    link_copied: '¡Enlace copiado!',
    tip_transactions: 'Transacciones',
    no_tips: 'Sin propinas aún',
    share_qr_tips: '¡Comparte tu código QR!',
    pending: 'Pendiente',
    completed: 'Completado',
    rejected: 'Rechazado',
    // ── Auth: Register ──────────────────────────────────────────────────────────
    reg_create_account: 'Crear tu cuenta',
    reg_first_name: 'Nombre',
    reg_last_name: 'Apellido',
    reg_email_ph: 'tu@ejemplo.com',
    reg_send_code: 'Enviar código de verificación',
    reg_sending: 'Enviando...',
    reg_secure: 'Seguro y cifrado',
    reg_check_email: 'Revisa tu correo',
    reg_code_sent_to: 'Enviamos un código de 6 dígitos a',
    reg_verify_code: 'Verificar código',
    reg_verifying: 'Verificando...',
    reg_change_email: '← Cambiar correo',
    reg_resend_code: 'Reenviar código',
    reg_create_creds: 'Crear credenciales',
    reg_username: 'usuario',
    reg_pw_min: 'Contraseña (mín. 6 caracteres)',
    reg_confirm_pw: 'Confirmar contraseña',
    reg_account_type: 'Tipo de cuenta',
    reg_individual: 'Individual',
    reg_i_work_alone: 'Trabajo solo',
    reg_business_label: 'Empresa',
    reg_i_manage_team: 'Gestiono un equipo',
    reg_select_country: 'Selecciona tu país',
    reg_select_country_ph: 'Selecciona tu país',
    reg_create_btn: 'Crear cuenta',
    reg_creating: 'Creando...',
    reg_back: '← Volver',
    reg_add_photo: 'Añade tu foto',
    reg_add_photo_desc: 'Añade una foto para que los clientes te reconozcan.',
    reg_change_photo: 'Cambiar foto',
    reg_add_photo_btn: 'Añadir foto',
    reg_job_title_ph: 'Cargo (ej. Camarero, Guía turístico)',
    reg_complete_setup: 'Completar configuración',
    reg_skip: 'Omitir por ahora',
    reg_profile_photo: 'Foto de perfil',
    reg_already: '¿Ya tienes una cuenta?',
    reg_login_link: 'Iniciar sesión',
    // ── Auth: Login ─────────────────────────────────────────────────────────────
    login_welcome: 'Bienvenido de nuevo',
    login_email_user: 'Correo o usuario',
    login_password_label: 'Contraseña',
    login_log_in: 'Iniciar sesión',
    login_logging_in: 'Iniciando sesión...',
    login_forgot_pw: '¿Olvidaste tu contraseña?',
    login_no_account: '¿No tienes cuenta?',
    login_sign_up: 'Registrarse',
    // ── Auth: Forgot Password ───────────────────────────────────────────────────
    fp_reset_pw: 'Restablecer contraseña',
    fp_all_done: '¡Todo listo!',
    fp_enter_email_hint: 'Ingresa tu correo para recibir un código de restablecimiento',
    fp_code_sent_to: 'Enviamos un código de 6 dígitos a',
    fp_pw_reset_done: 'Tu contraseña ha sido restablecida',
    fp_email_label: 'Correo electrónico',
    fp_email_ph: 'tu@ejemplo.com',
    fp_code_label: 'Código de verificación',
    fp_new_pw_label: 'Nueva contraseña',
    fp_pw_min_ph: 'Mín. 6 caracteres',
    fp_confirm_pw_label: 'Confirmar contraseña',
    fp_confirm_ph: 'Confirmar contraseña',
    fp_send_reset: 'Enviar código de restablecimiento',
    fp_reset_btn: 'Restablecer contraseña',
    fp_resetting: 'Restableciendo...',
    fp_login_new_pw: 'Iniciar sesión con nueva contraseña',
    fp_back_to_email: 'Volver al correo',
    fp_back_to_login: 'Volver al inicio de sesión',
    fp_success_title: '¡Contraseña restablecida!',
    fp_success_desc: 'Ahora puedes iniciar sesión con tu nueva contraseña.',
  },
};

const LANG_INFO: Record<string, { label: string; flag: string }> = {
  en: { label: 'English', flag: '🇬🇧' },
  fr: { label: 'Français', flag: '🇫🇷' },
  ar: { label: 'العربية', flag: '🇲🇦' },
  es: { label: 'Español', flag: '🇪🇸' },
};

type LanguageContextType = {
  language: string;
  changeLanguage: (lang: string) => Promise<void>;
  t: (key: string) => string;
  isRTL: boolean;
  languageLabel: string;
  LANG_INFO: Record<string, { label: string; flag: string }>;
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  changeLanguage: async () => {},
  t: (key) => key,
  isRTL: false,
  languageLabel: 'English',
  LANG_INFO,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState('en');
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    AsyncStorage.getItem(LANGUAGE_KEY).then((saved) => {
      if (saved && translations[saved]) {
        setLanguage(saved);
        I18nManager.forceRTL(saved === 'ar');
      }
      setLoaded(true);
    });
  }, []);

  const changeLanguage = useCallback(async (lang: string) => {
    if (!translations[lang]) return;
    setLanguage(lang);
    I18nManager.forceRTL(lang === 'ar');
    await AsyncStorage.setItem(LANGUAGE_KEY, lang);
  }, []);

  const t = useCallback(
    (key: string): string => {
      return translations[language]?.[key] || translations['en']?.[key] || key;
    },
    [language]
  );

  const isRTL = language === 'ar';
  const languageLabel = LANG_INFO[language]?.label || 'English';

  if (!loaded) return null;

  return (
    <LanguageContext.Provider
      value={{ language, changeLanguage, t, isRTL, languageLabel, LANG_INFO }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
export default LanguageContext;
