import { createContext, useContext, useState, useCallback, useEffect, type ReactNode } from 'react';
import { I18nManager } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';

I18nManager.allowRTL(true);

const LANGUAGE_KEY = 'snaptip_language';

const translations: Record<string, Record<string, string>> = {
  en: {
    // Navigation
    home: 'Home',
    tips: 'Tips',
    profile: 'Profile',
    // Home / Dashboard
    available_balance: 'Available Balance',
    total_earned: 'Total Earned',
    tips_received: 'Tips Received',
    tip_link_ready: 'Your tip link is ready',
    copy_link: 'Copy Link',
    share_qr: 'Share QR',
    manage_team: 'Manage Your Team',
    add_members: 'Add members, send invites',
    cash_out: 'Cash Out',
    my_qr: 'My QR',
    recent_tips: 'Recent Tips',
    view_all: 'View All',
    no_tips_yet: 'No tips yet',
    no_tips_desc: 'Share your QR code to start receiving tips from customers',
    show_my_qr: 'Show My QR',
    quick_actions: 'Quick Actions',
    my_qr_code_action: 'My QR Code',
    share_download_qr: 'Share & download your tip QR',
    withdraw_earnings: 'Withdraw Earnings',
    request_earnings_payout: 'Request your earnings payout',
    profile_settings: 'Profile & Settings',
    photo_name_language: 'Photo, name, language',
    // Profile
    my_profile: 'My Profile',
    settings_preferences: 'Settings & preferences',
    personal_info: 'Personal Info',
    full_name: 'Full Name',
    job_title: 'Job Title',
    save_profile: 'Save Profile',
    saving: 'Saving...',
    your_workplace: 'Your Workplace',
    member_account: 'Member account',
    active: 'Active',
    workplace_note: 'Your workplace can only be changed by your manager',
    withdrawal_settings: 'Withdrawal Settings',
    update_payment: 'Update Payment Method',
    payment_methods_desc: 'CIH Bank · Cash Plus · Wafa Cash',
    security: 'Security',
    change_password: 'Change Password',
    current_password: 'Current Password',
    new_password: 'New Password',
    confirm_password: 'Confirm New Password',
    save_password: 'Save Password',
    payment_method: 'Payment Method',
    rib_account: 'RIB / Account Number',
    enter_account: 'Enter account number',
    save_method: 'Save Method',
    account_settings: 'Account Settings',
    edit_profile: 'Edit Profile',
    business_settings: 'Business Settings',
    my_team: 'My Team',
    manage_members: 'Manage team members',
    invite_members: 'Invite Members',
    send_invitations: 'Send invitations',
    withdraw_funds: 'Withdraw Funds',
    recent_withdrawals: 'Recent Withdrawals',
    logout: 'Log Out',
    language: 'Language',
    change_photo: 'Change Photo',
    take_photo: 'Take Photo',
    choose_gallery: 'Choose from Gallery',
    settings: 'Settings',
    select_language: 'Select Language',
    // QR Card
    my_qr_card: 'My QR Card',
    download_share_subtitle: 'Download & share your printable tip card',
    download_share_card: 'Download & Share Card',
    preparing: 'Preparing...',
    preview_tourist_page: 'Preview Tourist Page',
    printing_tip: 'Printing tip',
    printing_tip_desc: 'Download the card as a PDF and print it for your table. Customers scan the QR to tip you — no app needed.',
    enjoyed: 'Enjoyed the service?',
    leave_tip: 'Leave a tip!',
    secure: 'Secure payment via SnapTip',
    select_amount: 'Choose tip amount',
    pay: 'Pay',
    save: 'Save',
    // Withdraw
    withdraw_title: 'Withdraw Earnings',
    request_payout: 'Request your payout',
    withdrawal_history: 'Withdrawal History',
    no_withdrawals: 'No withdrawals yet',
    no_withdrawals_desc: 'Your withdrawal history will appear here',
    amount: 'Amount',
    method: 'Method',
    submit_request: 'Submit Request',
    submitting: 'Submitting...',
    you_will_receive: 'You will receive:',
    available: 'Available:',
    enter_details: 'Enter account details',
    tip_received: 'Tip received',
    // Common
    cancel: 'Cancel',
    back: 'Back',
    confirm: 'Confirm',
    link_copied: 'Link copied!',
    // Tips screen
    tip_transactions: 'Tip Transactions',
    no_tips: 'No tips yet',
    share_qr_tips: 'Share your QR code to start receiving tips!',
    // Status
    pending: 'Pending',
    completed: 'Completed',
    rejected: 'Rejected',
    // ── Auth: Register ──────────────────────────────────────────────────────────
    reg_create_account: 'Create your account',
    reg_first_name: 'First name',
    reg_last_name: 'Last name',
    reg_email_ph: 'you@example.com',
    reg_send_code: 'Send Verification Code',
    reg_sending: 'Sending...',
    reg_secure: 'Secure & encrypted',
    reg_check_email: 'Check your email',
    reg_code_sent_to: 'We sent a 6-digit code to',
    reg_verify_code: 'Verify Code',
    reg_verifying: 'Verifying...',
    reg_change_email: '← Change email',
    reg_resend_code: 'Resend code',
    reg_create_creds: 'Create credentials',
    reg_username: 'username',
    reg_pw_min: 'Password (min 6 characters)',
    reg_confirm_pw: 'Confirm password',
    reg_account_type: 'Account Type',
    reg_individual: 'Individual',
    reg_i_work_alone: 'I work alone',
    reg_business_label: 'Business',
    reg_i_manage_team: 'I manage a team',
    reg_select_country: 'Select Your Country',
    reg_select_country_ph: 'Select your country',
    reg_create_btn: 'Create Account',
    reg_creating: 'Creating...',
    reg_back: '← Back',
    reg_add_photo: 'Add your photo',
    reg_add_photo_desc: 'Add a photo so customers can recognize you.',
    reg_change_photo: 'Change photo',
    reg_add_photo_btn: 'Add photo',
    reg_job_title_ph: 'Job title (e.g. Waiter, Tour Guide)',
    reg_complete_setup: 'Complete Setup',
    reg_skip: 'Skip for now',
    reg_profile_photo: 'Profile Photo',
    reg_already: 'Already have an account?',
    reg_login_link: 'Log in',
    // ── Auth: Login ─────────────────────────────────────────────────────────────
    login_welcome: 'Welcome back',
    login_email_user: 'Email or Username',
    login_password_label: 'Password',
    login_log_in: 'Log In',
    login_logging_in: 'Logging in...',
    login_forgot_pw: 'Forgot your password?',
    login_no_account: "Don't have an account?",
    login_sign_up: 'Sign up',
    // ── Auth: Forgot Password ───────────────────────────────────────────────────
    fp_reset_pw: 'Reset Password',
    fp_all_done: 'All Done!',
    fp_enter_email_hint: 'Enter your email to receive a reset code',
    fp_code_sent_to: 'We sent a 6-digit code to',
    fp_pw_reset_done: 'Your password has been reset',
    fp_email_label: 'Email Address',
    fp_email_ph: 'you@example.com',
    fp_code_label: 'Verification Code',
    fp_new_pw_label: 'New Password',
    fp_pw_min_ph: 'Min 6 characters',
    fp_confirm_pw_label: 'Confirm Password',
    fp_confirm_ph: 'Confirm password',
    fp_send_reset: 'Send Reset Code',
    fp_reset_btn: 'Reset Password',
    fp_resetting: 'Resetting...',
    fp_login_new_pw: 'Login with New Password',
    fp_back_to_email: 'Back to email',
    fp_back_to_login: 'Back to Login',
    fp_success_title: 'Password Reset Successfully!',
    fp_success_desc: 'You can now log in with your new password.',
  },
  fr: {
    home: 'Accueil',
    tips: 'Pourboires',
    profile: 'Profil',
    available_balance: 'Solde disponible',
    total_earned: 'Total gagné',
    tips_received: 'Pourboires reçus',
    tip_link_ready: 'Votre lien est prêt',
    copy_link: 'Copier le lien',
    share_qr: 'Partager QR',
    manage_team: 'Gérer votre équipe',
    add_members: 'Ajouter des membres',
    cash_out: 'Retirer',
    my_qr: 'Mon QR',
    recent_tips: 'Pourboires récents',
    view_all: 'Voir tout',
    no_tips_yet: 'Pas encore de pourboires',
    no_tips_desc: 'Partagez votre QR code pour recevoir des pourboires',
    show_my_qr: 'Afficher mon QR',
    quick_actions: 'Actions rapides',
    my_qr_code_action: 'Mon code QR',
    share_download_qr: 'Partager et télécharger votre QR',
    withdraw_earnings: 'Retirer les gains',
    request_earnings_payout: 'Demander un paiement',
    profile_settings: 'Profil et paramètres',
    photo_name_language: 'Photo, nom, langue',
    my_profile: 'Mon Profil',
    settings_preferences: 'Paramètres et préférences',
    personal_info: 'Informations personnelles',
    full_name: 'Nom complet',
    job_title: 'Poste',
    save_profile: 'Enregistrer le profil',
    saving: 'Enregistrement...',
    your_workplace: 'Votre lieu de travail',
    member_account: 'Compte membre',
    active: 'Actif',
    workplace_note: 'Votre lieu de travail ne peut être changé que par votre responsable',
    withdrawal_settings: 'Paramètres de retrait',
    update_payment: 'Modifier le moyen de paiement',
    payment_methods_desc: 'CIH Bank · Cash Plus · Wafa Cash',
    security: 'Sécurité',
    change_password: 'Changer le mot de passe',
    current_password: 'Mot de passe actuel',
    new_password: 'Nouveau mot de passe',
    confirm_password: 'Confirmer le nouveau mot de passe',
    save_password: 'Enregistrer le mot de passe',
    payment_method: 'Moyen de paiement',
    rib_account: 'RIB / Numéro de compte',
    enter_account: 'Entrer le numéro de compte',
    save_method: 'Enregistrer la méthode',
    account_settings: 'Paramètres du compte',
    edit_profile: 'Modifier le profil',
    business_settings: 'Paramètres entreprise',
    my_team: 'Mon équipe',
    manage_members: 'Gérer les membres',
    invite_members: 'Inviter des membres',
    send_invitations: 'Envoyer des invitations',
    withdraw_funds: 'Retirer des fonds',
    recent_withdrawals: 'Retraits récents',
    logout: 'Se déconnecter',
    language: 'Langue',
    change_photo: 'Changer la photo',
    take_photo: 'Prendre une photo',
    choose_gallery: 'Choisir depuis la galerie',
    settings: 'Paramètres',
    select_language: 'Choisir la langue',
    my_qr_card: 'Ma carte QR',
    download_share_subtitle: 'Téléchargez et partagez votre carte',
    download_share_card: 'Télécharger et partager',
    preparing: 'Préparation...',
    preview_tourist_page: 'Aperçu page touriste',
    printing_tip: "Conseil d'impression",
    printing_tip_desc: "Téléchargez la carte en PDF et imprimez-la pour votre table. Les clients scannent le QR pour vous donner un pourboire.",
    enjoyed: 'Vous avez apprécié le service?',
    leave_tip: 'Laissez un pourboire!',
    secure: 'Paiement sécurisé via SnapTip',
    select_amount: 'Choisir le montant',
    pay: 'Payer',
    save: 'Enregistrer',
    withdraw_title: 'Retirer les gains',
    request_payout: 'Demander votre paiement',
    withdrawal_history: 'Historique des retraits',
    no_withdrawals: 'Aucun retrait',
    no_withdrawals_desc: 'Votre historique de retraits apparaîtra ici',
    amount: 'Montant',
    method: 'Méthode',
    submit_request: 'Soumettre la demande',
    submitting: 'Envoi en cours...',
    you_will_receive: 'Vous recevrez :',
    available: 'Disponible :',
    enter_details: 'Entrer les détails du compte',
    tip_received: 'Pourboire reçu',
    cancel: 'Annuler',
    back: 'Retour',
    confirm: 'Confirmer',
    link_copied: 'Lien copié !',
    tip_transactions: 'Transactions',
    no_tips: 'Pas encore de pourboires',
    share_qr_tips: 'Partagez votre QR code !',
    pending: 'En attente',
    completed: 'Terminé',
    rejected: 'Rejeté',
    // ── Auth: Register ──────────────────────────────────────────────────────────
    reg_create_account: 'Créer votre compte',
    reg_first_name: 'Prénom',
    reg_last_name: 'Nom',
    reg_email_ph: 'vous@exemple.com',
    reg_send_code: 'Envoyer le code de vérification',
    reg_sending: 'Envoi...',
    reg_secure: 'Sécurisé et chiffré',
    reg_check_email: 'Vérifiez votre e-mail',
    reg_code_sent_to: 'Nous avons envoyé un code à 6 chiffres à',
    reg_verify_code: 'Vérifier le code',
    reg_verifying: 'Vérification...',
    reg_change_email: '← Changer l\'e-mail',
    reg_resend_code: 'Renvoyer le code',
    reg_create_creds: 'Créer vos identifiants',
    reg_username: 'nom d\'utilisateur',
    reg_pw_min: 'Mot de passe (min 6 caractères)',
    reg_confirm_pw: 'Confirmer le mot de passe',
    reg_account_type: 'Type de compte',
    reg_individual: 'Individuel',
    reg_i_work_alone: 'Je travaille seul',
    reg_business_label: 'Entreprise',
    reg_i_manage_team: 'Je gère une équipe',
    reg_select_country: 'Sélectionner votre pays',
    reg_select_country_ph: 'Sélectionner votre pays',
    reg_create_btn: 'Créer un compte',
    reg_creating: 'Création...',
    reg_back: '← Retour',
    reg_add_photo: 'Ajouter votre photo',
    reg_add_photo_desc: 'Ajoutez une photo pour que les clients vous reconnaissent.',
    reg_change_photo: 'Changer la photo',
    reg_add_photo_btn: 'Ajouter une photo',
    reg_job_title_ph: 'Poste (ex. Serveur, Guide touristique)',
    reg_complete_setup: 'Terminer la configuration',
    reg_skip: 'Ignorer pour l\'instant',
    reg_profile_photo: 'Photo de profil',
    reg_already: 'Vous avez déjà un compte ?',
    reg_login_link: 'Se connecter',
    // ── Auth: Login ─────────────────────────────────────────────────────────────
    login_welcome: 'Bon retour',
    login_email_user: 'E-mail ou nom d\'utilisateur',
    login_password_label: 'Mot de passe',
    login_log_in: 'Se connecter',
    login_logging_in: 'Connexion...',
    login_forgot_pw: 'Mot de passe oublié ?',
    login_no_account: 'Pas encore de compte ?',
    login_sign_up: "S'inscrire",
    // ── Auth: Forgot Password ───────────────────────────────────────────────────
    fp_reset_pw: 'Réinitialiser le mot de passe',
    fp_all_done: 'Tout est fait !',
    fp_enter_email_hint: 'Entrez votre e-mail pour recevoir un code de réinitialisation',
    fp_code_sent_to: 'Nous avons envoyé un code à 6 chiffres à',
    fp_pw_reset_done: 'Votre mot de passe a été réinitialisé',
    fp_email_label: 'Adresse e-mail',
    fp_email_ph: 'vous@exemple.com',
    fp_code_label: 'Code de vérification',
    fp_new_pw_label: 'Nouveau mot de passe',
    fp_pw_min_ph: 'Min 6 caractères',
    fp_confirm_pw_label: 'Confirmer le mot de passe',
    fp_confirm_ph: 'Confirmer le mot de passe',
    fp_send_reset: 'Envoyer le code de réinitialisation',
    fp_reset_btn: 'Réinitialiser le mot de passe',
    fp_resetting: 'Réinitialisation...',
    fp_login_new_pw: 'Se connecter avec le nouveau mot de passe',
    fp_back_to_email: "Retour à l'e-mail",
    fp_back_to_login: 'Retour à la connexion',
    fp_success_title: 'Mot de passe réinitialisé !',
    fp_success_desc: 'Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.',
  },
  ar: {
    home: 'الرئيسية',
    tips: 'إكراميات',
    profile: 'الملف',
    available_balance: 'الرصيد المتاح',
    total_earned: 'إجمالي الأرباح',
    tips_received: 'إكراميات مستلمة',
    tip_link_ready: 'رابط الإكرامية جاهز',
    copy_link: 'نسخ الرابط',
    share_qr: 'مشاركة QR',
    manage_team: 'إدارة فريقك',
    add_members: 'إضافة أعضاء',
    cash_out: 'سحب',
    my_qr: 'رمز QR',
    recent_tips: 'إكراميات أخيرة',
    view_all: 'عرض الكل',
    no_tips_yet: 'لا إكراميات بعد',
    no_tips_desc: 'شارك رمز QR لبدء استلام الإكراميات',
    show_my_qr: 'عرض رمز QR',
    quick_actions: 'إجراءات سريعة',
    my_qr_code_action: 'رمز QR الخاص بي',
    share_download_qr: 'مشاركة وتحميل رمز QR',
    withdraw_earnings: 'سحب الأرباح',
    request_earnings_payout: 'طلب صرف الأرباح',
    profile_settings: 'الملف والإعدادات',
    photo_name_language: 'الصورة, الاسم, اللغة',
    my_profile: 'ملفي الشخصي',
    settings_preferences: 'الإعدادات والتفضيلات',
    personal_info: 'المعلومات الشخصية',
    full_name: 'الاسم الكامل',
    job_title: 'المسمى الوظيفي',
    save_profile: 'حفظ الملف',
    saving: 'جاري الحفظ...',
    your_workplace: 'مكان عملك',
    member_account: 'حساب عضو',
    active: 'نشط',
    workplace_note: 'لا يمكن تغيير مكان عملك إلا من قبل مديرك',
    withdrawal_settings: 'إعدادات السحب',
    update_payment: 'تحديث طريقة الدفع',
    payment_methods_desc: 'CIH Bank · Cash Plus · Wafa Cash',
    security: 'الأمان',
    change_password: 'تغيير كلمة المرور',
    current_password: 'كلمة المرور الحالية',
    new_password: 'كلمة المرور الجديدة',
    confirm_password: 'تأكيد كلمة المرور',
    save_password: 'حفظ كلمة المرور',
    payment_method: 'طريقة الدفع',
    rib_account: 'RIB / رقم الحساب',
    enter_account: 'أدخل رقم الحساب',
    save_method: 'حفظ الطريقة',
    account_settings: 'إعدادات الحساب',
    edit_profile: 'تعديل الملف',
    business_settings: 'إعدادات العمل',
    my_team: 'فريقي',
    manage_members: 'إدارة الأعضاء',
    invite_members: 'دعوة أعضاء',
    send_invitations: 'إرسال دعوات',
    withdraw_funds: 'سحب الأموال',
    recent_withdrawals: 'سحوبات أخيرة',
    logout: 'تسجيل الخروج',
    language: 'اللغة',
    change_photo: 'تغيير الصورة',
    take_photo: 'التقاط صورة',
    choose_gallery: 'اختيار من المعرض',
    settings: 'الإعدادات',
    select_language: 'اختر اللغة',
    my_qr_card: 'بطاقة QR',
    download_share_subtitle: 'حمل وشارك بطاقتك القابلة للطباعة',
    download_share_card: 'تحميل ومشاركة البطاقة',
    preparing: 'جاري التحضير...',
    preview_tourist_page: 'معاينة صفحة الدفع',
    printing_tip: 'نصيحة للطباعة',
    printing_tip_desc: 'حمّل البطاقة كملف PDF واطبعها لطاولتك. يمسح العملاء رمز QR لإعطائك إكرامية.',
    enjoyed: 'هل استمتعت بالخدمة؟',
    leave_tip: '!اترك بقشيشاً',
    secure: 'دفع آمن عبر SnapTip',
    select_amount: 'اختر المبلغ',
    pay: 'ادفع',
    save: 'حفظ',
    withdraw_title: 'سحب الأرباح',
    request_payout: 'طلب صرف الأرباح',
    withdrawal_history: 'سجل السحوبات',
    no_withdrawals: 'لا توجد سحوبات',
    no_withdrawals_desc: 'سيظهر سجل السحوبات هنا',
    amount: 'المبلغ',
    method: 'الطريقة',
    submit_request: 'إرسال الطلب',
    submitting: 'جاري الإرسال...',
    you_will_receive: 'ستتلقى:',
    available: 'المتاح:',
    enter_details: 'أدخل تفاصيل الحساب',
    tip_received: 'إكرامية مستلمة',
    cancel: 'إلغاء',
    back: 'رجوع',
    confirm: 'تأكيد',
    link_copied: 'تم نسخ الرابط!',
    tip_transactions: 'المعاملات',
    no_tips: 'لا إكراميات بعد',
    share_qr_tips: 'شارك رمز QR لبدء استلام الإكراميات!',
    pending: 'قيد الانتظار',
    completed: 'مكتمل',
    rejected: 'مرفوض',
    // ── Auth: Register ──────────────────────────────────────────────────────────
    reg_create_account: 'إنشاء حسابك',
    reg_first_name: 'الاسم الأول',
    reg_last_name: 'اسم العائلة',
    reg_email_ph: 'you@example.com',
    reg_send_code: 'إرسال رمز التحقق',
    reg_sending: 'جاري الإرسال...',
    reg_secure: 'آمن ومشفر',
    reg_check_email: 'تحقق من بريدك الإلكتروني',
    reg_code_sent_to: 'أرسلنا رمزاً من 6 أرقام إلى',
    reg_verify_code: 'التحقق من الرمز',
    reg_verifying: 'جاري التحقق...',
    reg_change_email: '← تغيير البريد',
    reg_resend_code: 'إعادة إرسال الرمز',
    reg_create_creds: 'إنشاء بيانات الاعتماد',
    reg_username: 'اسم المستخدم',
    reg_pw_min: 'كلمة المرور (6 أحرف على الأقل)',
    reg_confirm_pw: 'تأكيد كلمة المرور',
    reg_account_type: 'نوع الحساب',
    reg_individual: 'فردي',
    reg_i_work_alone: 'أعمل بمفردي',
    reg_business_label: 'شركة',
    reg_i_manage_team: 'أدير فريقاً',
    reg_select_country: 'اختر دولتك',
    reg_select_country_ph: 'اختر دولتك',
    reg_create_btn: 'إنشاء حساب',
    reg_creating: 'جاري الإنشاء...',
    reg_back: '← رجوع',
    reg_add_photo: 'أضف صورتك',
    reg_add_photo_desc: 'أضف صورة حتى يتعرف عليك العملاء.',
    reg_change_photo: 'تغيير الصورة',
    reg_add_photo_btn: 'إضافة صورة',
    reg_job_title_ph: 'المسمى الوظيفي (مثال: نادل، مرشد سياحي)',
    reg_complete_setup: 'إكمال الإعداد',
    reg_skip: 'تخطي الآن',
    reg_profile_photo: 'صورة الملف الشخصي',
    reg_already: 'هل لديك حساب بالفعل؟',
    reg_login_link: 'تسجيل الدخول',
    // ── Auth: Login ─────────────────────────────────────────────────────────────
    login_welcome: 'مرحباً بعودتك',
    login_email_user: 'البريد الإلكتروني أو اسم المستخدم',
    login_password_label: 'كلمة المرور',
    login_log_in: 'تسجيل الدخول',
    login_logging_in: 'جاري الدخول...',
    login_forgot_pw: 'نسيت كلمة المرور؟',
    login_no_account: 'ليس لديك حساب؟',
    login_sign_up: 'إنشاء حساب',
    // ── Auth: Forgot Password ───────────────────────────────────────────────────
    fp_reset_pw: 'إعادة تعيين كلمة المرور',
    fp_all_done: 'تم بنجاح!',
    fp_enter_email_hint: 'أدخل بريدك الإلكتروني لاستلام رمز إعادة التعيين',
    fp_code_sent_to: 'أرسلنا رمزاً من 6 أرقام إلى',
    fp_pw_reset_done: 'تم إعادة تعيين كلمة مرورك',
    fp_email_label: 'البريد الإلكتروني',
    fp_email_ph: 'you@example.com',
    fp_code_label: 'رمز التحقق',
    fp_new_pw_label: 'كلمة المرور الجديدة',
    fp_pw_min_ph: '6 أحرف على الأقل',
    fp_confirm_pw_label: 'تأكيد كلمة المرور',
    fp_confirm_ph: 'تأكيد كلمة المرور',
    fp_send_reset: 'إرسال رمز الإعادة',
    fp_reset_btn: 'إعادة تعيين كلمة المرور',
    fp_resetting: 'جاري الإعادة...',
    fp_login_new_pw: 'الدخول بكلمة المرور الجديدة',
    fp_back_to_email: 'العودة للبريد',
    fp_back_to_login: 'العودة لتسجيل الدخول',
    fp_success_title: 'تمت إعادة تعيين كلمة المرور!',
    fp_success_desc: 'يمكنك الآن تسجيل الدخول بكلمة مرورك الجديدة.',
  },
  es: {
    home: 'Inicio',
    tips: 'Propinas',
    profile: 'Perfil',
    available_balance: 'Saldo disponible',
    total_earned: 'Total ganado',
    tips_received: 'Propinas recibidas',
    tip_link_ready: 'Tu enlace está listo',
    copy_link: 'Copiar enlace',
    share_qr: 'Compartir QR',
    manage_team: 'Gestionar equipo',
    add_members: 'Añadir miembros',
    cash_out: 'Retirar',
    my_qr: 'Mi QR',
    recent_tips: 'Propinas recientes',
    view_all: 'Ver todo',
    no_tips_yet: 'Sin propinas aún',
    no_tips_desc: 'Comparte tu QR para empezar a recibir propinas',
    show_my_qr: 'Mostrar mi QR',
    quick_actions: 'Acciones rápidas',
    my_qr_code_action: 'Mi código QR',
    share_download_qr: 'Comparte y descarga tu QR',
    withdraw_earnings: 'Retirar ganancias',
    request_earnings_payout: 'Solicitar pago de ganancias',
    profile_settings: 'Perfil y ajustes',
    photo_name_language: 'Foto, nombre, idioma',
    my_profile: 'Mi Perfil',
    settings_preferences: 'Ajustes y preferencias',
    personal_info: 'Información personal',
    full_name: 'Nombre completo',
    job_title: 'Cargo',
    save_profile: 'Guardar perfil',
    saving: 'Guardando...',
    your_workplace: 'Tu lugar de trabajo',
    member_account: 'Cuenta de miembro',
    active: 'Activo',
    workplace_note: 'Tu lugar de trabajo solo puede ser cambiado por tu gerente',
    withdrawal_settings: 'Ajustes de retiro',
    update_payment: 'Actualizar método de pago',
    payment_methods_desc: 'CIH Bank · Cash Plus · Wafa Cash',
    security: 'Seguridad',
    change_password: 'Cambiar contraseña',
    current_password: 'Contraseña actual',
    new_password: 'Nueva contraseña',
    confirm_password: 'Confirmar nueva contraseña',
    save_password: 'Guardar contraseña',
    payment_method: 'Método de pago',
    rib_account: 'RIB / Número de cuenta',
    enter_account: 'Ingresa el número de cuenta',
    save_method: 'Guardar método',
    account_settings: 'Configuración',
    edit_profile: 'Editar perfil',
    business_settings: 'Ajustes de negocio',
    my_team: 'Mi equipo',
    manage_members: 'Gestionar miembros',
    invite_members: 'Invitar miembros',
    send_invitations: 'Enviar invitaciones',
    withdraw_funds: 'Retirar fondos',
    recent_withdrawals: 'Retiros recientes',
    logout: 'Cerrar sesión',
    language: 'Idioma',
    change_photo: 'Cambiar foto',
    take_photo: 'Tomar foto',
    choose_gallery: 'Elegir de galería',
    settings: 'Configuración',
    select_language: 'Seleccionar idioma',
    my_qr_card: 'Mi tarjeta QR',
    download_share_subtitle: 'Descarga y comparte tu tarjeta imprimible',
    download_share_card: 'Descargar y compartir',
    preparing: 'Preparando...',
    preview_tourist_page: 'Vista previa página turista',
    printing_tip: 'Consejo de impresión',
    printing_tip_desc: 'Descarga la tarjeta como PDF e imprímela para tu mesa. Los clientes escanean el QR para darte propina.',
    enjoyed: '¿Disfrutaste el servicio?',
    leave_tip: '¡Deja una propina!',
    secure: 'Pago seguro via SnapTip',
    select_amount: 'Elige el monto',
    pay: 'Pagar',
    save: 'Guardar',
    withdraw_title: 'Retirar ganancias',
    request_payout: 'Solicitar tu pago',
    withdrawal_history: 'Historial de retiros',
    no_withdrawals: 'Sin retiros aún',
    no_withdrawals_desc: 'Tu historial de retiros aparecerá aquí',
    amount: 'Monto',
    method: 'Método',
    submit_request: 'Enviar solicitud',
    submitting: 'Enviando...',
    you_will_receive: 'Recibirás:',
    available: 'Disponible:',
    enter_details: 'Ingresa los datos de la cuenta',
    tip_received: 'Propina recibida',
    cancel: 'Cancelar',
    back: 'Volver',
    confirm: 'Confirmar',
    link_copied: '¡Enlace copiado!',
    tip_transactions: 'Transacciones',
    no_tips: 'Sin propinas aún',
    share_qr_tips: '¡Comparte tu código QR!',
    pending: 'Pendiente',
    completed: 'Completado',
    rejected: 'Rechazado',
    // ── Auth: Register ──────────────────────────────────────────────────────────
    reg_create_account: 'Crear tu cuenta',
    reg_first_name: 'Nombre',
    reg_last_name: 'Apellido',
    reg_email_ph: 'tu@ejemplo.com',
    reg_send_code: 'Enviar código de verificación',
    reg_sending: 'Enviando...',
    reg_secure: 'Seguro y cifrado',
    reg_check_email: 'Revisa tu correo',
    reg_code_sent_to: 'Enviamos un código de 6 dígitos a',
    reg_verify_code: 'Verificar código',
    reg_verifying: 'Verificando...',
    reg_change_email: '← Cambiar correo',
    reg_resend_code: 'Reenviar código',
    reg_create_creds: 'Crear credenciales',
    reg_username: 'usuario',
    reg_pw_min: 'Contraseña (mín. 6 caracteres)',
    reg_confirm_pw: 'Confirmar contraseña',
    reg_account_type: 'Tipo de cuenta',
    reg_individual: 'Individual',
    reg_i_work_alone: 'Trabajo solo',
    reg_business_label: 'Empresa',
    reg_i_manage_team: 'Gestiono un equipo',
    reg_select_country: 'Selecciona tu país',
    reg_select_country_ph: 'Selecciona tu país',
    reg_create_btn: 'Crear cuenta',
    reg_creating: 'Creando...',
    reg_back: '← Volver',
    reg_add_photo: 'Añade tu foto',
    reg_add_photo_desc: 'Añade una foto para que los clientes te reconozcan.',
    reg_change_photo: 'Cambiar foto',
    reg_add_photo_btn: 'Añadir foto',
    reg_job_title_ph: 'Cargo (ej. Camarero, Guía turístico)',
    reg_complete_setup: 'Completar configuración',
    reg_skip: 'Omitir por ahora',
    reg_profile_photo: 'Foto de perfil',
    reg_already: '¿Ya tienes una cuenta?',
    reg_login_link: 'Iniciar sesión',
    // ── Auth: Login ─────────────────────────────────────────────────────────────
    login_welcome: 'Bienvenido de nuevo',
    login_email_user: 'Correo o usuario',
    login_password_label: 'Contraseña',
    login_log_in: 'Iniciar sesión',
    login_logging_in: 'Iniciando sesión...',
    login_forgot_pw: '¿Olvidaste tu contraseña?',
    login_no_account: '¿No tienes cuenta?',
    login_sign_up: 'Registrarse',
    // ── Auth: Forgot Password ───────────────────────────────────────────────────
    fp_reset_pw: 'Restablecer contraseña',
    fp_all_done: '¡Todo listo!',
    fp_enter_email_hint: 'Ingresa tu correo para recibir un código de restablecimiento',
    fp_code_sent_to: 'Enviamos un código de 6 dígitos a',
    fp_pw_reset_done: 'Tu contraseña ha sido restablecida',
    fp_email_label: 'Correo electrónico',
    fp_email_ph: 'tu@ejemplo.com',
    fp_code_label: 'Código de verificación',
    fp_new_pw_label: 'Nueva contraseña',
    fp_pw_min_ph: 'Mín. 6 caracteres',
    fp_confirm_pw_label: 'Confirmar contraseña',
    fp_confirm_ph: 'Confirmar contraseña',
    fp_send_reset: 'Enviar código de restablecimiento',
    fp_reset_btn: 'Restablecer contraseña',
    fp_resetting: 'Restableciendo...',
    fp_login_new_pw: 'Iniciar sesión con nueva contraseña',
    fp_back_to_email: 'Volver al correo',
    fp_back_to_login: 'Volver al inicio de sesión',
    fp_success_title: '¡Contraseña restablecida!',
    fp_success_desc: 'Ahora puedes iniciar sesión con tu nueva contraseña.',
  },
};

const EXTRA_TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    member: 'Member',
    welcome: 'Welcome',
    live: 'Live',
    this_month: 'This Month',
    tips_count_label: 'Tips',
    my_rating: 'My Rating',
    rating_singular: 'rating',
    rating_plural: 'ratings',
    no_ratings_yet: 'No ratings yet',
    receive_tips_collect_ratings: 'Receive tips to collect star ratings',
    received_from: 'Received from',
    colleague: 'Colleague',
    split_tip: 'Split Tip',
    withdraw: 'Withdraw',
    total_withdrawn: 'Total Withdrawn',
    cash_out_earnings: 'Cash out your earnings',
    country: 'Country',
    show_my_rating: 'Show my rating',
    show_my_rating_desc: 'Display your rating on your dashboard',
    contact_support: 'Contact Support',
    contact_support_desc: 'Get help from our team',
    your_full_name: 'Your full name',
    save_changes: 'Save Changes',
    permission_required: 'Permission Required',
    camera_permission_required: 'Camera access is required. Please enable it in your device Settings.',
    photo_library_permission_required: 'Photo library access is required. Please enable it in your device Settings.',
    could_not_process_image: 'Could not process image.',
    server_error: 'Server error',
    photo_updated: 'Photo updated!',
    no_photo_url: 'No photo URL in server response',
    could_not_save_photo: 'Could not save your photo. {message}',
    unknown_error: 'Unknown error',
    name_required: 'Name is required.',
    profile_updated: 'Profile updated!',
    failed_update: 'Failed to update.',
    are_you_sure: 'Are you sure?',
    tip_received_toast: '+{amount} {currency} tip received!',
    no_funds_withdraw: 'No funds to withdraw.',
    minimum_withdrawal_is: 'Minimum withdrawal is {amount} {currency}.',
    minimum_withdrawal_balance: 'Minimum withdrawal is {amount} {currency}. Your balance is {balance} {currency}.',
    enter_valid_amount: 'Enter a valid amount.',
    minimum_is_for_method: 'Minimum is {amount} {currency} for {method}.',
    insufficient_balance: 'Insufficient balance.',
    field_required: '{field} is required.',
    must_be_exact_digits: 'Must be exactly {count} digits.',
    morocco_phone_error: 'Must start with 06 or 07 and be 10 digits.',
    iban_error: 'IBAN must start with 2 letters, min 15 characters.',
    swift_error: 'SWIFT/BIC must be 8 or 11 characters.',
    fix_errors_below: 'Please fix the errors below.',
    failed_submit: 'Failed to submit.',
    paid: 'Paid',
    balance_deducted_on_request: 'Balance deducted immediately on request',
    available_to_withdraw: 'Available to withdraw',
    select_payment_method: 'Select Payment Method',
    transfer_method: 'Transfer Method',
    tap_to_choose_option: 'Tap to choose option',
    fee: 'Fee',
    no_fee: 'No Fee',
    min: 'Min',
    choose_receive_funds: 'Choose how to receive your funds',
    amount_currency: 'Amount ({currency})',
    max: 'MAX',
    requested: 'Requested',
    processing_fee: 'Processing Fee',
    wise_fee: 'Wise Fee (~0.5%)',
    free: 'Free',
    estimated_received: 'Estimated received',
    payment_method_label: 'Payment Method',
    processing_time: 'Processing Time',
    wise_fee_note: 'Note: Actual Wise fees may vary slightly',
    request_withdrawal: 'Request Withdrawal',
    withdrawal_requested: 'Withdrawal Requested!',
    withdrawal_success_body: 'Your request for {amount} {currency} has been submitted.\nWe will process it within {time}.\nYou will receive an email confirmation.',
    you_receive: 'You receive',
    via_method: 'via {method}',
    done: 'Done',
    qr_code_not_available: 'QR code not available yet',
    username_not_setup_desc: 'Your username has not been set up.\nContact support or complete your profile.',
    customize_your_card: 'Customize Your Card',
    custom_message: 'Custom Message',
    leave_tip_default: 'Leave a tip!  (default)',
    show_profile_photo: 'Show Profile Photo',
    show_profile_photo_desc: 'Display your photo on the card',
    apply_changes: 'Apply Changes',
    card_settings_saved: 'Card settings saved!',
    failed_save_settings: 'Failed to save settings.',
    cannot_generate_qr: 'Cannot generate QR - username not set up yet.',
    qr_card_ready: 'QR Card ready!',
    failed_generate_card: 'Failed to generate card.',
    username_not_setup: 'Username not set up yet.',
    could_not_open_browser: 'Could not open browser.',
    withdraw_field_full_name: 'Full Name',
    withdraw_field_cin: 'CIN / ID Number',
    withdraw_field_contact_phone: 'Contact Phone',
    withdraw_field_phone: 'Phone Number',
    withdraw_field_rib: 'RIB / Account Number',
    withdraw_field_bank_name: 'Bank Name',
    withdraw_field_iban: 'IBAN',
    withdraw_field_swift: 'SWIFT / BIC Code',
    withdraw_field_routing_number: 'Routing Number',
    withdraw_field_account_number: 'Account Number',
    withdraw_placeholder_full_name: 'Your full legal name',
    withdraw_placeholder_cin: 'AB123456',
    withdraw_placeholder_contact_phone: 'Phone number',
    withdraw_placeholder_phone: 'Phone number',
    withdraw_placeholder_rib: 'Account number',
    withdraw_placeholder_bank_name: 'Bank name',
    withdraw_placeholder_iban: 'IBAN',
    withdraw_placeholder_swift: 'SWIFT / BIC',
    withdraw_placeholder_routing_number: 'Routing number',
    withdraw_placeholder_account_number: 'Bank account number',
    code_sent_to: 'Code sent to {email}',
    failed_send_code: 'Failed to send code.',
    email_verified: 'Email verified!',
    verification_failed: 'Verification failed.',
    enter_full_code: 'Enter the full 6-digit code.',
    new_code_sent: 'New code sent!',
    failed_generic: 'Failed.',
    account_created: 'Account created!',
    registration_failed: 'Registration failed.',
    photo_upload_failed: 'Photo upload failed',
    profile_photo_uploaded: 'Profile photo uploaded!',
    setup_complete: 'Setup complete!',
    could_not_save_profile: 'Could not save your profile. {message}',
    valid_email_required: 'Enter a valid email address.',
    reset_code_sent: 'Reset code sent to your email.',
    failed_send_reset_code: 'Failed to send reset code.',
    password_min_error: 'Password must be at least 6 characters.',
    passwords_do_not_match: 'Passwords do not match.',
    password_reset_success: 'Password reset successfully!',
    failed_reset_password: 'Failed to reset password.',
    all_fields_required: 'All fields are required.',
    invalid_credentials: 'Invalid credentials.',
    failed_save_profile: 'Failed to save profile.',
    password_changed: 'Password changed!',
    failed_change_password: 'Failed to change password.',
    select_method: 'Select a method.',
    withdrawal_settings_saved: 'Withdrawal settings saved!',
    failed_save: 'Failed to save.',
    failed_load_dashboard: 'Failed to load dashboard.',
  },
  fr: {
    dashboard: 'Tableau de bord',
    member: 'Membre',
    welcome: 'Bienvenue',
    live: 'En direct',
    this_month: 'Ce mois-ci',
    tips_count_label: 'Pourboires',
    my_rating: 'Ma note',
    rating_singular: 'note',
    rating_plural: 'notes',
    no_ratings_yet: 'Aucune note pour le moment',
    receive_tips_collect_ratings: 'Recevez des pourboires pour collecter des notes',
    received_from: 'Recu de',
    colleague: 'Collegue',
    split_tip: 'Pourboire partage',
    withdraw: 'Retirer',
    total_withdrawn: 'Total retire',
    cash_out_earnings: 'Retirez vos gains',
    country: 'Pays',
    show_my_rating: 'Afficher ma note',
    show_my_rating_desc: 'Afficher votre note sur votre tableau de bord',
    contact_support: 'Contacter le support',
    contact_support_desc: 'Obtenir de l aide de notre equipe',
    your_full_name: 'Votre nom complet',
    save_changes: 'Enregistrer',
    permission_required: 'Autorisation requise',
    camera_permission_required: 'L acces a la camera est requis. Activez-le dans les reglages de votre appareil.',
    photo_library_permission_required: 'L acces a la galerie est requis. Activez-le dans les reglages de votre appareil.',
    could_not_process_image: 'Impossible de traiter l image.',
    server_error: 'Erreur serveur',
    photo_updated: 'Photo mise a jour !',
    no_photo_url: 'Aucune URL de photo dans la reponse serveur',
    could_not_save_photo: 'Impossible d enregistrer votre photo. {message}',
    unknown_error: 'Erreur inconnue',
    name_required: 'Le nom est requis.',
    profile_updated: 'Profil mis a jour !',
    failed_update: 'Echec de la mise a jour.',
    are_you_sure: 'Etes-vous sur ?',
    tip_received_toast: '+{amount} {currency} de pourboire recu !',
    no_funds_withdraw: 'Aucun fonds a retirer.',
    minimum_withdrawal_is: 'Le retrait minimum est de {amount} {currency}.',
    minimum_withdrawal_balance: 'Le retrait minimum est de {amount} {currency}. Votre solde est de {balance} {currency}.',
    enter_valid_amount: 'Entrez un montant valide.',
    minimum_is_for_method: 'Le minimum est de {amount} {currency} pour {method}.',
    insufficient_balance: 'Solde insuffisant.',
    field_required: '{field} est requis.',
    must_be_exact_digits: 'Doit contenir exactement {count} chiffres.',
    morocco_phone_error: 'Doit commencer par 06 ou 07 et contenir 10 chiffres.',
    iban_error: 'L IBAN doit commencer par 2 lettres et contenir au moins 15 caracteres.',
    swift_error: 'Le SWIFT/BIC doit contenir 8 ou 11 caracteres.',
    fix_errors_below: 'Corrigez les erreurs ci-dessous.',
    failed_submit: 'Echec de l envoi.',
    paid: 'Paye',
    balance_deducted_on_request: 'Solde deduit immediatement apres la demande',
    available_to_withdraw: 'Disponible au retrait',
    select_payment_method: 'Selectionner le moyen de paiement',
    transfer_method: 'Methode de transfert',
    tap_to_choose_option: 'Touchez pour choisir',
    fee: 'Frais',
    no_fee: 'Sans frais',
    min: 'Min',
    choose_receive_funds: 'Choisissez comment recevoir vos fonds',
    amount_currency: 'Montant ({currency})',
    max: 'MAX',
    requested: 'Demande',
    processing_fee: 'Frais de traitement',
    wise_fee: 'Frais Wise (~0,5 %)',
    free: 'Gratuit',
    estimated_received: 'Montant estime',
    payment_method_label: 'Moyen de paiement',
    processing_time: 'Delai de traitement',
    wise_fee_note: 'Note : les frais Wise reels peuvent varier legerement',
    request_withdrawal: 'Demander le retrait',
    withdrawal_requested: 'Retrait demande !',
    withdrawal_success_body: 'Votre demande de {amount} {currency} a ete envoyee.\nNous la traiterons sous {time}.\nVous recevrez une confirmation par e-mail.',
    you_receive: 'Vous recevez',
    via_method: 'via {method}',
    done: 'Termine',
    qr_code_not_available: 'Code QR pas encore disponible',
    username_not_setup_desc: 'Votre nom d utilisateur n est pas encore configure.\nContactez le support ou completez votre profil.',
    customize_your_card: 'Personnaliser votre carte',
    custom_message: 'Message personnalise',
    leave_tip_default: 'Laissez un pourboire ! (par defaut)',
    show_profile_photo: 'Afficher la photo de profil',
    show_profile_photo_desc: 'Afficher votre photo sur la carte',
    apply_changes: 'Appliquer',
    card_settings_saved: 'Parametres de carte enregistres !',
    failed_save_settings: 'Echec de l enregistrement.',
    cannot_generate_qr: 'Impossible de generer le QR - nom d utilisateur manquant.',
    qr_card_ready: 'Carte QR prete !',
    failed_generate_card: 'Echec de la generation de la carte.',
    username_not_setup: 'Nom d utilisateur non configure.',
    could_not_open_browser: 'Impossible d ouvrir le navigateur.',
    withdraw_field_full_name: 'Nom complet',
    withdraw_field_cin: 'CIN / Piece d identite',
    withdraw_field_contact_phone: 'Telephone de contact',
    withdraw_field_phone: 'Numero de telephone',
    withdraw_field_rib: 'RIB / Numero de compte',
    withdraw_field_bank_name: 'Nom de la banque',
    withdraw_field_iban: 'IBAN',
    withdraw_field_swift: 'Code SWIFT / BIC',
    withdraw_field_routing_number: 'Routing number',
    withdraw_field_account_number: 'Numero de compte',
    withdraw_placeholder_full_name: 'Votre nom legal complet',
    withdraw_placeholder_cin: 'AB123456',
    withdraw_placeholder_contact_phone: 'Numero de telephone',
    withdraw_placeholder_phone: 'Numero de telephone',
    withdraw_placeholder_rib: 'Numero de compte',
    withdraw_placeholder_bank_name: 'Nom de la banque',
    withdraw_placeholder_iban: 'IBAN',
    withdraw_placeholder_swift: 'SWIFT / BIC',
    withdraw_placeholder_routing_number: 'Routing number',
    withdraw_placeholder_account_number: 'Numero de compte bancaire',
    code_sent_to: 'Code envoye a {email}',
    failed_send_code: 'Echec de l envoi du code.',
    email_verified: 'E-mail verifie !',
    verification_failed: 'Echec de la verification.',
    enter_full_code: 'Entrez le code complet a 6 chiffres.',
    new_code_sent: 'Nouveau code envoye !',
    failed_generic: 'Echec.',
    account_created: 'Compte cree !',
    registration_failed: 'Echec de l inscription.',
    photo_upload_failed: 'Echec de l envoi de la photo',
    profile_photo_uploaded: 'Photo de profil envoyee !',
    setup_complete: 'Configuration terminee !',
    could_not_save_profile: 'Impossible d enregistrer votre profil. {message}',
    valid_email_required: 'Entrez une adresse e-mail valide.',
    reset_code_sent: 'Code de reinitialisation envoye par e-mail.',
    failed_send_reset_code: 'Echec de l envoi du code.',
    password_min_error: 'Le mot de passe doit contenir au moins 6 caracteres.',
    passwords_do_not_match: 'Les mots de passe ne correspondent pas.',
    password_reset_success: 'Mot de passe reinitialise !',
    failed_reset_password: 'Echec de la reinitialisation du mot de passe.',
    all_fields_required: 'Tous les champs sont requis.',
    invalid_credentials: 'Identifiants invalides.',
    failed_save_profile: 'Echec de l enregistrement du profil.',
    password_changed: 'Mot de passe modifie !',
    failed_change_password: 'Echec du changement de mot de passe.',
    select_method: 'Selectionnez une methode.',
    withdrawal_settings_saved: 'Parametres de retrait enregistres !',
    failed_save: 'Echec de l enregistrement.',
    failed_load_dashboard: 'Echec du chargement du tableau de bord.',
  },
  ar: {
    dashboard: 'لوحة التحكم',
    member: 'عضو',
    welcome: 'مرحبا',
    live: 'مباشر',
    this_month: 'هذا الشهر',
    tips_count_label: 'البقشيش',
    my_rating: 'تقييمي',
    rating_singular: 'تقييم',
    rating_plural: 'تقييمات',
    no_ratings_yet: 'لا توجد تقييمات بعد',
    receive_tips_collect_ratings: 'استقبل بقشيشا لجمع التقييمات',
    received_from: 'استلمت من',
    colleague: 'زميل',
    split_tip: 'بقشيش مشترك',
    withdraw: 'سحب',
    total_withdrawn: 'إجمالي السحوبات',
    cash_out_earnings: 'اسحب أرباحك',
    country: 'البلد',
    show_my_rating: 'إظهار تقييمي',
    show_my_rating_desc: 'اعرض تقييمك في لوحة التحكم',
    contact_support: 'اتصل بالدعم',
    contact_support_desc: 'احصل على مساعدة من فريقنا',
    your_full_name: 'اسمك الكامل',
    save_changes: 'حفظ التغييرات',
    permission_required: 'الإذن مطلوب',
    camera_permission_required: 'الوصول إلى الكاميرا مطلوب. يرجى تفعيله من إعدادات الجهاز.',
    photo_library_permission_required: 'الوصول إلى الصور مطلوب. يرجى تفعيله من إعدادات الجهاز.',
    could_not_process_image: 'تعذر معالجة الصورة.',
    server_error: 'خطأ في الخادم',
    photo_updated: 'تم تحديث الصورة!',
    no_photo_url: 'لا يوجد رابط صورة في رد الخادم',
    could_not_save_photo: 'تعذر حفظ صورتك. {message}',
    unknown_error: 'خطأ غير معروف',
    name_required: 'الاسم مطلوب.',
    profile_updated: 'تم تحديث الملف!',
    failed_update: 'فشل التحديث.',
    are_you_sure: 'هل أنت متأكد؟',
    tip_received_toast: '+{amount} {currency} بقشيش مستلم!',
    no_funds_withdraw: 'لا توجد أموال للسحب.',
    minimum_withdrawal_is: 'الحد الأدنى للسحب هو {amount} {currency}.',
    minimum_withdrawal_balance: 'الحد الأدنى للسحب هو {amount} {currency}. رصيدك هو {balance} {currency}.',
    enter_valid_amount: 'أدخل مبلغا صالحا.',
    minimum_is_for_method: 'الحد الأدنى هو {amount} {currency} لطريقة {method}.',
    insufficient_balance: 'الرصيد غير كاف.',
    field_required: '{field} مطلوب.',
    must_be_exact_digits: 'يجب أن يكون {count} أرقاما بالضبط.',
    morocco_phone_error: 'يجب أن يبدأ ب 06 أو 07 ويتكون من 10 أرقام.',
    iban_error: 'يجب أن يبدأ IBAN بحرفين وأن لا يقل عن 15 حرفا.',
    swift_error: 'يجب أن يكون SWIFT/BIC من 8 أو 11 حرفا.',
    fix_errors_below: 'يرجى تصحيح الأخطاء أدناه.',
    failed_submit: 'فشل الإرسال.',
    paid: 'مدفوع',
    balance_deducted_on_request: 'يتم خصم الرصيد مباشرة عند الطلب',
    available_to_withdraw: 'متاح للسحب',
    select_payment_method: 'اختر طريقة الدفع',
    transfer_method: 'طريقة التحويل',
    tap_to_choose_option: 'اضغط للاختيار',
    fee: 'رسوم',
    no_fee: 'بدون رسوم',
    min: 'الحد الأدنى',
    choose_receive_funds: 'اختر طريقة استلام أموالك',
    amount_currency: 'المبلغ ({currency})',
    max: 'الكل',
    requested: 'المبلغ المطلوب',
    processing_fee: 'رسوم المعالجة',
    wise_fee: 'رسوم Wise (~0.5%)',
    free: 'مجاني',
    estimated_received: 'المبلغ المتوقع',
    payment_method_label: 'طريقة الدفع',
    processing_time: 'مدة المعالجة',
    wise_fee_note: 'ملاحظة: قد تختلف رسوم Wise قليلا',
    request_withdrawal: 'طلب السحب',
    withdrawal_requested: 'تم طلب السحب!',
    withdrawal_success_body: 'تم إرسال طلبك بمبلغ {amount} {currency}.\nسنعالجه خلال {time}.\nستتلقى تأكيدا عبر البريد الإلكتروني.',
    you_receive: 'ستستلم',
    via_method: 'عبر {method}',
    done: 'تم',
    qr_code_not_available: 'رمز QR غير متاح بعد',
    username_not_setup_desc: 'لم يتم إعداد اسم المستخدم الخاص بك.\nاتصل بالدعم أو أكمل ملفك.',
    customize_your_card: 'تخصيص بطاقتك',
    custom_message: 'رسالة مخصصة',
    leave_tip_default: 'اترك بقشيشا! (افتراضي)',
    show_profile_photo: 'إظهار صورة الملف',
    show_profile_photo_desc: 'اعرض صورتك على البطاقة',
    apply_changes: 'تطبيق التغييرات',
    card_settings_saved: 'تم حفظ إعدادات البطاقة!',
    failed_save_settings: 'فشل حفظ الإعدادات.',
    cannot_generate_qr: 'تعذر إنشاء QR - اسم المستخدم غير مهيأ.',
    qr_card_ready: 'بطاقة QR جاهزة!',
    failed_generate_card: 'فشل إنشاء البطاقة.',
    username_not_setup: 'اسم المستخدم غير مهيأ بعد.',
    could_not_open_browser: 'تعذر فتح المتصفح.',
    withdraw_field_full_name: 'الاسم الكامل',
    withdraw_field_cin: 'رقم البطاقة / CIN',
    withdraw_field_contact_phone: 'هاتف التواصل',
    withdraw_field_phone: 'رقم الهاتف',
    withdraw_field_rib: 'RIB / رقم الحساب',
    withdraw_field_bank_name: 'اسم البنك',
    withdraw_field_iban: 'IBAN',
    withdraw_field_swift: 'رمز SWIFT / BIC',
    withdraw_field_routing_number: 'رقم التوجيه',
    withdraw_field_account_number: 'رقم الحساب',
    withdraw_placeholder_full_name: 'اسمك القانوني الكامل',
    withdraw_placeholder_cin: 'AB123456',
    withdraw_placeholder_contact_phone: 'رقم الهاتف',
    withdraw_placeholder_phone: 'رقم الهاتف',
    withdraw_placeholder_rib: 'رقم الحساب',
    withdraw_placeholder_bank_name: 'اسم البنك',
    withdraw_placeholder_iban: 'IBAN',
    withdraw_placeholder_swift: 'SWIFT / BIC',
    withdraw_placeholder_routing_number: 'رقم التوجيه',
    withdraw_placeholder_account_number: 'رقم الحساب البنكي',
    code_sent_to: 'تم إرسال الرمز إلى {email}',
    failed_send_code: 'فشل إرسال الرمز.',
    email_verified: 'تم تأكيد البريد!',
    verification_failed: 'فشل التحقق.',
    enter_full_code: 'أدخل الرمز الكامل المكون من 6 أرقام.',
    new_code_sent: 'تم إرسال رمز جديد!',
    failed_generic: 'فشل.',
    account_created: 'تم إنشاء الحساب!',
    registration_failed: 'فشل التسجيل.',
    photo_upload_failed: 'فشل رفع الصورة',
    profile_photo_uploaded: 'تم رفع صورة الملف!',
    setup_complete: 'اكتمل الإعداد!',
    could_not_save_profile: 'تعذر حفظ ملفك. {message}',
    valid_email_required: 'أدخل بريدا إلكترونيا صالحا.',
    reset_code_sent: 'تم إرسال رمز إعادة التعيين إلى بريدك.',
    failed_send_reset_code: 'فشل إرسال رمز إعادة التعيين.',
    password_min_error: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل.',
    passwords_do_not_match: 'كلمتا المرور غير متطابقتين.',
    password_reset_success: 'تمت إعادة تعيين كلمة المرور!',
    failed_reset_password: 'فشل إعادة تعيين كلمة المرور.',
    all_fields_required: 'كل الحقول مطلوبة.',
    invalid_credentials: 'بيانات الدخول غير صحيحة.',
    failed_save_profile: 'فشل حفظ الملف.',
    password_changed: 'تم تغيير كلمة المرور!',
    failed_change_password: 'فشل تغيير كلمة المرور.',
    select_method: 'اختر طريقة.',
    withdrawal_settings_saved: 'تم حفظ إعدادات السحب!',
    failed_save: 'فشل الحفظ.',
    failed_load_dashboard: 'فشل تحميل لوحة التحكم.',
  },
  es: {
    dashboard: 'Panel',
    member: 'Miembro',
    welcome: 'Bienvenido',
    live: 'En vivo',
    this_month: 'Este mes',
    tips_count_label: 'Propinas',
    my_rating: 'Mi valoracion',
    rating_singular: 'valoracion',
    rating_plural: 'valoraciones',
    no_ratings_yet: 'Sin valoraciones aun',
    receive_tips_collect_ratings: 'Recibe propinas para reunir valoraciones',
    received_from: 'Recibido de',
    colleague: 'Colega',
    split_tip: 'Propina compartida',
    withdraw: 'Retirar',
    total_withdrawn: 'Total retirado',
    cash_out_earnings: 'Retira tus ganancias',
    country: 'Pais',
    show_my_rating: 'Mostrar mi valoracion',
    show_my_rating_desc: 'Mostrar tu valoracion en el panel',
    contact_support: 'Contactar soporte',
    contact_support_desc: 'Recibe ayuda de nuestro equipo',
    your_full_name: 'Tu nombre completo',
    save_changes: 'Guardar cambios',
    permission_required: 'Permiso requerido',
    camera_permission_required: 'Se requiere acceso a la camara. Activalo en los ajustes del dispositivo.',
    photo_library_permission_required: 'Se requiere acceso a la galeria. Activalo en los ajustes del dispositivo.',
    could_not_process_image: 'No se pudo procesar la imagen.',
    server_error: 'Error del servidor',
    photo_updated: 'Foto actualizada!',
    no_photo_url: 'No hay URL de foto en la respuesta del servidor',
    could_not_save_photo: 'No se pudo guardar tu foto. {message}',
    unknown_error: 'Error desconocido',
    name_required: 'El nombre es obligatorio.',
    profile_updated: 'Perfil actualizado!',
    failed_update: 'No se pudo actualizar.',
    are_you_sure: 'Estas seguro?',
    tip_received_toast: '+{amount} {currency} de propina recibida!',
    no_funds_withdraw: 'No hay fondos para retirar.',
    minimum_withdrawal_is: 'El retiro minimo es {amount} {currency}.',
    minimum_withdrawal_balance: 'El retiro minimo es {amount} {currency}. Tu saldo es {balance} {currency}.',
    enter_valid_amount: 'Introduce un importe valido.',
    minimum_is_for_method: 'El minimo es {amount} {currency} para {method}.',
    insufficient_balance: 'Saldo insuficiente.',
    field_required: '{field} es obligatorio.',
    must_be_exact_digits: 'Debe tener exactamente {count} digitos.',
    morocco_phone_error: 'Debe empezar por 06 o 07 y tener 10 digitos.',
    iban_error: 'El IBAN debe empezar con 2 letras y tener minimo 15 caracteres.',
    swift_error: 'El SWIFT/BIC debe tener 8 u 11 caracteres.',
    fix_errors_below: 'Corrige los errores indicados.',
    failed_submit: 'No se pudo enviar.',
    paid: 'Pagado',
    balance_deducted_on_request: 'El saldo se descuenta inmediatamente al solicitar',
    available_to_withdraw: 'Disponible para retirar',
    select_payment_method: 'Seleccionar metodo de pago',
    transfer_method: 'Metodo de transferencia',
    tap_to_choose_option: 'Toca para elegir',
    fee: 'Comision',
    no_fee: 'Sin comision',
    min: 'Min',
    choose_receive_funds: 'Elige como recibir tus fondos',
    amount_currency: 'Importe ({currency})',
    max: 'MAX',
    requested: 'Solicitado',
    processing_fee: 'Comision de procesamiento',
    wise_fee: 'Comision Wise (~0,5 %)',
    free: 'Gratis',
    estimated_received: 'Recibido estimado',
    payment_method_label: 'Metodo de pago',
    processing_time: 'Tiempo de procesamiento',
    wise_fee_note: 'Nota: las comisiones reales de Wise pueden variar ligeramente',
    request_withdrawal: 'Solicitar retiro',
    withdrawal_requested: 'Retiro solicitado!',
    withdrawal_success_body: 'Tu solicitud de {amount} {currency} ha sido enviada.\nLa procesaremos en {time}.\nRecibiras una confirmacion por correo.',
    you_receive: 'Recibes',
    via_method: 'via {method}',
    done: 'Listo',
    qr_code_not_available: 'Codigo QR aun no disponible',
    username_not_setup_desc: 'Tu usuario aun no esta configurado.\nContacta con soporte o completa tu perfil.',
    customize_your_card: 'Personalizar tu tarjeta',
    custom_message: 'Mensaje personalizado',
    leave_tip_default: 'Deja una propina! (predeterminado)',
    show_profile_photo: 'Mostrar foto de perfil',
    show_profile_photo_desc: 'Mostrar tu foto en la tarjeta',
    apply_changes: 'Aplicar cambios',
    card_settings_saved: 'Ajustes de tarjeta guardados!',
    failed_save_settings: 'No se pudo guardar.',
    cannot_generate_qr: 'No se puede generar el QR - falta el usuario.',
    qr_card_ready: 'Tarjeta QR lista!',
    failed_generate_card: 'No se pudo generar la tarjeta.',
    username_not_setup: 'Usuario aun no configurado.',
    could_not_open_browser: 'No se pudo abrir el navegador.',
    withdraw_field_full_name: 'Nombre completo',
    withdraw_field_cin: 'CIN / Documento',
    withdraw_field_contact_phone: 'Telefono de contacto',
    withdraw_field_phone: 'Numero de telefono',
    withdraw_field_rib: 'RIB / Numero de cuenta',
    withdraw_field_bank_name: 'Nombre del banco',
    withdraw_field_iban: 'IBAN',
    withdraw_field_swift: 'Codigo SWIFT / BIC',
    withdraw_field_routing_number: 'Numero de ruta',
    withdraw_field_account_number: 'Numero de cuenta',
    withdraw_placeholder_full_name: 'Tu nombre legal completo',
    withdraw_placeholder_cin: 'AB123456',
    withdraw_placeholder_contact_phone: 'Numero de telefono',
    withdraw_placeholder_phone: 'Numero de telefono',
    withdraw_placeholder_rib: 'Numero de cuenta',
    withdraw_placeholder_bank_name: 'Nombre del banco',
    withdraw_placeholder_iban: 'IBAN',
    withdraw_placeholder_swift: 'SWIFT / BIC',
    withdraw_placeholder_routing_number: 'Numero de ruta',
    withdraw_placeholder_account_number: 'Numero de cuenta bancaria',
    code_sent_to: 'Codigo enviado a {email}',
    failed_send_code: 'No se pudo enviar el codigo.',
    email_verified: 'Correo verificado!',
    verification_failed: 'No se pudo verificar.',
    enter_full_code: 'Introduce el codigo completo de 6 digitos.',
    new_code_sent: 'Nuevo codigo enviado!',
    failed_generic: 'Error.',
    account_created: 'Cuenta creada!',
    registration_failed: 'No se pudo registrar.',
    photo_upload_failed: 'No se pudo subir la foto',
    profile_photo_uploaded: 'Foto de perfil subida!',
    setup_complete: 'Configuracion completa!',
    could_not_save_profile: 'No se pudo guardar tu perfil. {message}',
    valid_email_required: 'Introduce un correo valido.',
    reset_code_sent: 'Codigo de restablecimiento enviado a tu correo.',
    failed_send_reset_code: 'No se pudo enviar el codigo.',
    password_min_error: 'La contrasena debe tener al menos 6 caracteres.',
    passwords_do_not_match: 'Las contrasenas no coinciden.',
    password_reset_success: 'Contrasena restablecida!',
    failed_reset_password: 'No se pudo restablecer la contrasena.',
    all_fields_required: 'Todos los campos son obligatorios.',
    invalid_credentials: 'Credenciales invalidas.',
    failed_save_profile: 'No se pudo guardar el perfil.',
    password_changed: 'Contrasena cambiada!',
    failed_change_password: 'No se pudo cambiar la contrasena.',
    select_method: 'Selecciona un metodo.',
    withdrawal_settings_saved: 'Ajustes de retiro guardados!',
    failed_save: 'No se pudo guardar.',
    failed_load_dashboard: 'No se pudo cargar el panel.',
  },
};

Object.keys(EXTRA_TRANSLATIONS).forEach((lang) => {
  translations[lang] = {
    ...EXTRA_TRANSLATIONS.en,
    ...translations[lang],
    ...EXTRA_TRANSLATIONS[lang],
  };
});

const LANG_INFO: Record<string, { label: string; flag: string }> = {
  en: { label: 'English', flag: '🇬🇧' },
  fr: { label: 'Français', flag: '🇫🇷' },
  ar: { label: 'العربية', flag: '🇲🇦' },
  es: { label: 'Español', flag: '🇪🇸' },
};

type LanguageContextType = {
  language: string;
  changeLanguage: (lang: string) => Promise<void>;
  t: (key: string) => string;
  isRTL: boolean;
  languageLabel: string;
  LANG_INFO: Record<string, { label: string; flag: string }>;
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  changeLanguage: async () => {},
  t: (key) => key,
  isRTL: false,
  languageLabel: 'English',
  LANG_INFO,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState('en');
  const [loaded, setLoaded] = useState(false);

  useEffect(() => {
    AsyncStorage.getItem(LANGUAGE_KEY).then((saved) => {
      if (saved && translations[saved]) {
        setLanguage(saved);
        I18nManager.forceRTL(saved === 'ar');
      }
      setLoaded(true);
    });
  }, []);

  const changeLanguage = useCallback(async (lang: string) => {
    if (!translations[lang]) return;
    setLanguage(lang);
    I18nManager.forceRTL(lang === 'ar');
    await AsyncStorage.setItem(LANGUAGE_KEY, lang);
  }, []);

  const t = useCallback(
    (key: string): string => {
      return translations[language]?.[key] || translations['en']?.[key] || key;
    },
    [language]
  );

  const isRTL = language === 'ar';
  const languageLabel = LANG_INFO[language]?.label || 'English';

  if (!loaded) return null;

  return (
    <LanguageContext.Provider
      value={{ language, changeLanguage, t, isRTL, languageLabel, LANG_INFO }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
export default LanguageContext;
